import type { Store } from "@/types/cube";

function img(seed: string, w = 800, h = 800) {
  return `https://picsum.photos/seed/${seed}/${w}/${h}`;
}

export const mockStore: Store = {
  id: "riverside-market",
  name: "Riverside Market",
  cubes: [
    {
      id: "aurelia-jewelry",
      merchantName: "Aurelia",
      outletIds: ["tampines-hub", "pasir-ris-mall"],
      tagline: "Handmade fine jewelry, small batch",
      about:
        "Aurelia crafts every piece in-house using recycled gold and ethically sourced stones. Each cube rotation features a limited run of one-of-a-kind designs.",
      logo: img("aurelia-logo", 200, 200),
      products: [
        {
          id: "aurelia-ring-01",
          name: "Halo Solitaire Ring",
          price: 248,
          currency: "SGD",
          images: [img("aurelia-ring-01-a"), img("aurelia-ring-01-b")],
          description:
            "A delicate solitaire ring with a halo of pavé stones, set in 18k gold vermeil.",
          stockStatus: "in_stock",
          sizes: ["5", "6", "7", "8"],
          variants: [
            { label: "Gold", available: true },
            { label: "Rose Gold", available: true },
            { label: "Silver", available: false },
          ],
        },
        {
          id: "aurelia-necklace-01",
          name: "Thread Pendant Necklace",
          price: 168,
          currency: "SGD",
          images: [img("aurelia-necklace-01")],
          description:
            "Minimalist pendant on a fine cable chain, designed to be layered.",
          stockStatus: "low_stock",
          variants: [
            { label: "Gold", available: true },
            { label: "Silver", available: true },
          ],
        },
        {
          id: "aurelia-earring-01",
          name: "Drift Hoop Earrings",
          price: 132,
          currency: "SGD",
          images: [img("aurelia-earring-01")],
          description: "Lightweight hammered hoops with a brushed matte finish.",
          stockStatus: "in_stock",
        },
        {
          id: "aurelia-bracelet-01",
          name: "Linked Tennis Bracelet",
          price: 312,
          currency: "SGD",
          images: [img("aurelia-bracelet-01")],
          description: "Classic tennis bracelet with cubic zirconia links.",
          stockStatus: "out_of_stock",
        },
        {
          id: "aurelia-ring-02",
          name: "Stacked Band Set",
          price: 96,
          currency: "SGD",
          images: [img("aurelia-ring-02")],
          description: "Set of three stackable bands in mixed textures.",
          stockStatus: "in_stock",
          sizes: ["5", "6", "7", "8", "9"],
        },
        {
          id: "aurelia-anklet-01",
          name: "Sea Glass Anklet",
          price: 78,
          currency: "SGD",
          images: [img("aurelia-anklet-01")],
          description: "Beaded anklet with sea glass chips and a gold clasp.",
          stockStatus: "in_stock",
        },
      ],
    },
    {
      id: "kobo-ceramics",
      merchantName: "Kobo Ceramics",
      outletIds: ["tampines-hub"],
      tagline: "Stoneware for everyday rituals",
      about:
        "Kobo throws every piece by hand on a small wheel studio nearby. Glazes are mixed in-house, so colour and texture vary slightly between pieces — that's the point.",
      logo: img("kobo-logo", 200, 200),
      products: [
        {
          id: "kobo-mug-01",
          name: "Speckled Stoneware Mug",
          price: 38,
          currency: "SGD",
          images: [img("kobo-mug-01-a"), img("kobo-mug-01-b")],
          description: "A wide-bodied mug glazed in a warm speckled oatmeal tone.",
          stockStatus: "in_stock",
          variants: [
            { label: "Oatmeal", available: true },
            { label: "Slate", available: true },
            { label: "Moss", available: false },
          ],
        },
        {
          id: "kobo-bowl-01",
          name: "Nesting Bowl Set",
          price: 64,
          currency: "SGD",
          images: [img("kobo-bowl-01")],
          description: "Three nesting bowls in graduated sizes, glazed matte white.",
          stockStatus: "in_stock",
        },
        {
          id: "kobo-vase-01",
          name: "Tall Bud Vase",
          price: 52,
          currency: "SGD",
          images: [img("kobo-vase-01")],
          description: "A narrow-necked vase built for single stems.",
          stockStatus: "low_stock",
        },
        {
          id: "kobo-plate-01",
          name: "Side Plate, Set of 4",
          price: 72,
          currency: "SGD",
          images: [img("kobo-plate-01")],
          description: "Stackable side plates with a soft reactive glaze edge.",
          stockStatus: "in_stock",
        },
        {
          id: "kobo-teapot-01",
          name: "Single-Serve Teapot",
          price: 58,
          currency: "SGD",
          images: [img("kobo-teapot-01")],
          description: "Compact teapot with built-in strainer spout.",
          stockStatus: "out_of_stock",
        },
      ],
    },
    {
      id: "fernweh-apparel",
      merchantName: "Fernweh",
      outletIds: ["pasir-ris-mall", "woodleigh-mall"],
      tagline: "Travel-ready basics, cut to last",
      about:
        "Fernweh designs versatile layers for people who live out of a carry-on. Fabrics are chosen for packability and durability over trend cycles.",
      logo: img("fernweh-logo", 200, 200),
      products: [
        {
          id: "fernweh-tee-01",
          name: "Merino Travel Tee",
          price: 58,
          currency: "SGD",
          images: [img("fernweh-tee-01-a"), img("fernweh-tee-01-b")],
          description: "Odor-resistant merino blend tee that packs flat.",
          stockStatus: "in_stock",
          sizes: ["XS", "S", "M", "L", "XL"],
          variants: [
            { label: "Charcoal", available: true },
            { label: "Sand", available: true },
            { label: "Navy", available: true },
          ],
        },
        {
          id: "fernweh-jacket-01",
          name: "Packable Shell Jacket",
          price: 168,
          currency: "SGD",
          images: [img("fernweh-jacket-01")],
          description: "Water-resistant shell that folds into its own pocket.",
          stockStatus: "low_stock",
          sizes: ["S", "M", "L", "XL"],
        },
        {
          id: "fernweh-pants-01",
          name: "Stretch Travel Chino",
          price: 98,
          currency: "SGD",
          images: [img("fernweh-pants-01")],
          description: "Four-way stretch chino with a hidden zip pocket.",
          stockStatus: "in_stock",
          sizes: ["28", "30", "32", "34", "36"],
        },
        {
          id: "fernweh-socks-01",
          name: "Compression Travel Socks",
          price: 24,
          currency: "SGD",
          images: [img("fernweh-socks-01")],
          description: "Graduated compression socks for long flights.",
          stockStatus: "in_stock",
        },
        {
          id: "fernweh-bag-01",
          name: "Packing Cube Trio",
          price: 44,
          currency: "SGD",
          images: [img("fernweh-bag-01")],
          description: "Set of three compression packing cubes.",
          stockStatus: "in_stock",
        },
        {
          id: "fernweh-hat-01",
          name: "Crushable Travel Cap",
          price: 32,
          currency: "SGD",
          images: [img("fernweh-hat-01")],
          description: "Packable cap that springs back into shape.",
          stockStatus: "out_of_stock",
        },
      ],
    },
    {
      id: "verdant-botanicals",
      merchantName: "Verdant Botanicals",
      outletIds: ["pasir-ris-mall"],
      tagline: "Small-batch skincare, cold-pressed",
      about:
        "Verdant formulates every batch by hand using cold-press extraction to preserve actives. Bottled and labeled the same week it's made.",
      logo: img("verdant-logo", 200, 200),
      products: [
        {
          id: "verdant-serum-01",
          name: "Rosehip Repair Serum",
          price: 54,
          currency: "SGD",
          images: [img("verdant-serum-01")],
          description: "Cold-pressed rosehip oil serum for overnight repair.",
          stockStatus: "in_stock",
        },
        {
          id: "verdant-cleanser-01",
          name: "Oat Milk Cleanser",
          price: 36,
          currency: "SGD",
          images: [img("verdant-cleanser-01")],
          description: "Gentle cream cleanser for sensitive skin.",
          stockStatus: "in_stock",
        },
        {
          id: "verdant-mask-01",
          name: "Clay Detox Mask",
          price: 42,
          currency: "SGD",
          images: [img("verdant-mask-01")],
          description: "Kaolin clay mask with charcoal for deep pore cleansing.",
          stockStatus: "low_stock",
        },
        {
          id: "verdant-balm-01",
          name: "Calendula Lip Balm",
          price: 18,
          currency: "SGD",
          images: [img("verdant-balm-01")],
          description: "Calendula-infused balm for dry, chapped lips.",
          stockStatus: "in_stock",
          variants: [
            { label: "Unscented", available: true },
            { label: "Citrus", available: true },
          ],
        },
        {
          id: "verdant-mist-01",
          name: "Rosewater Face Mist",
          price: 28,
          currency: "SGD",
          images: [img("verdant-mist-01")],
          description: "Hydrating rosewater mist for midday refresh.",
          stockStatus: "out_of_stock",
        },
      ],
    },
    {
      id: "northpeak-coffee",
      merchantName: "Northpeak Coffee",
      outletIds: ["woodleigh-mall", "tampines-hub"],
      tagline: "Single-origin beans, roasted weekly",
      about:
        "Northpeak roasts in small batches every week and sells out fast. Beans are sourced directly from smallholder farms across three regions.",
      logo: img("northpeak-logo", 200, 200),
      products: [
        {
          id: "northpeak-beans-01",
          name: "Ethiopia Yirgacheffe, 250g",
          price: 26,
          currency: "SGD",
          images: [img("northpeak-beans-01")],
          description: "Light roast with bright citrus and floral notes.",
          stockStatus: "in_stock",
        },
        {
          id: "northpeak-beans-02",
          name: "Colombia Huila, 250g",
          price: 24,
          currency: "SGD",
          images: [img("northpeak-beans-02")],
          description: "Medium roast with caramel sweetness and a clean finish.",
          stockStatus: "in_stock",
        },
        {
          id: "northpeak-beans-03",
          name: "Sumatra Mandheling, 250g",
          price: 25,
          currency: "SGD",
          images: [img("northpeak-beans-03")],
          description: "Dark roast, full-bodied with earthy, herbal notes.",
          stockStatus: "low_stock",
        },
        {
          id: "northpeak-drip-01",
          name: "Pour-Over Filter Pack",
          price: 14,
          currency: "SGD",
          images: [img("northpeak-drip-01")],
          description: "Pack of 50 unbleached pour-over filters.",
          stockStatus: "in_stock",
        },
        {
          id: "northpeak-mug-01",
          name: "Northpeak House Mug",
          price: 22,
          currency: "SGD",
          images: [img("northpeak-mug-01")],
          description: "Branded ceramic mug, holds 350ml.",
          stockStatus: "out_of_stock",
        },
      ],
    },
  ],
};
